version: '3.7'

services:

  web:
    image: discovervlad/rq-test:0.0.1
    container_name: web
    ports:
      - '5004:5000'
    command: python manage.py run -h 0.0.0.0
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.server.config.DevelopmentConfig
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    image: discovervlad/rq-worker:0.0.1
    command: python manage_worker.py run_worker
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.server.config.DevelopmentConfig
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:5.0.3-alpine

  dashboard:
    image: discovervlad/rq-dashboard:0.0.1
    container_name: dashboard
    ports:
      - '9181:9181'
    environment:
      - REDIS_URL=redis://redis:6379/0
